Repository pnpm/pnpm, pull requests merged in 2019-10, with the labels that each got.

#2043 feat: use cross-platform solution to clone packages
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/package-store/package.json
  packages/package-store/src/fs/importIndexedDir.ts
  packages/package-store/src/storeController/createImportPackage.ts
  packages/package-store/src/storeController/index.ts
  packages/package-store/test/createImportPackage.spec.ts
  packages/package-store/test/index.ts
  packages/pnpm/src/cmd/help.ts
  packages/supi/test/install/misc.ts
  packages/types/src/options.ts
  pnpm-lock.yaml
Labels: type: breaking change

#2044 feat: drop Node.js 8 support
  .travis.yml
  appveyor.yml
  packages/build-modules/package.json
  packages/config/package.json
  packages/constants/package.json
  packages/core-loggers/package.json
  packages/default-fetcher/package.json
  packages/default-reporter/package.json
  packages/default-resolver/package.json
  packages/dependencies-hierarchy/package.json
  packages/dependency-path/package.json
  packages/error/package.json
  packages/fetch-from-npm-registry/package.json
  packages/fetch/package.json
  packages/fetcher-base/package.json
  packages/filter-lockfile/package.json
  packages/find-packages/package.json
  packages/git-fetcher/package.json
  packages/git-resolver/package.json
  packages/headless/package.json
  packages/hoist/package.json
  packages/lifecycle/package.json
  packages/list/package.json
  packages/local-resolver/package.json
  packages/lockfile-file/package.json
  packages/lockfile-types/package.json
  packages/lockfile-utils/package.json
  packages/modules-cleaner/package.json
  packages/modules-yaml/package.json
  packages/npm-registry-agent/package.json
  packages/npm-resolver/package.json
  packages/outdated/package.json
  packages/package-is-installable/package.json
  packages/package-requester/package.json
  packages/package-store/package.json
  packages/pkgs-graph/package.json
  packages/pnpm/package.json
  packages/prune-lockfile/package.json
  packages/read-importer-manifest/package.json
  packages/read-importers-context/package.json
  packages/read-modules-dir/package.json
  packages/read-package-json/package.json
  packages/resolve-dependencies/package.json
  packages/resolver-base/package.json
  packages/server/package.json
  packages/store-controller-types/package.json
  packages/supi/package.json
  packages/symlink-dependency/package.json
  packages/tarball-fetcher/package.json
  packages/tarball-resolver/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/write-importer-manifest/package.json
  privatePackages/assert-project/package.json
  privatePackages/assert-store/package.json
  utils/tslint-config/package.json
Labels: type: breaking change

#2052 feat: new matching pattern
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/config/test/index.ts
  packages/dependencies-hierarchy/package.json
  packages/dependencies-hierarchy/src/index.ts
  packages/dependencies-hierarchy/test/index.ts
  packages/headless/package.json
  packages/headless/src/index.ts
  packages/hoist/package.json
  packages/hoist/src/index.ts
  packages/list/package.json
  packages/list/src/createPackagesSearcher.ts
  packages/list/src/index.ts
  packages/list/test/createPackagesSearcher.spec.ts
  packages/list/test/index.ts
  packages/matcher/README.md
  packages/matcher/package.json
  packages/matcher/src/index.ts
  packages/matcher/test/index.ts
  packages/matcher/tsconfig.json
  packages/matcher/tslint.json
  packages/modules-yaml/src/index.ts
  packages/outdated/package.json
  packages/outdated/src/index.ts
  packages/outdated/test/index.ts
  packages/pnpm/package.json
  packages/pnpm/src/cmd/outdated.ts
  packages/pnpm/src/cmd/recursive/filter.ts
  packages/pnpm/test/link.ts
  packages/pnpm/test/recursive/misc.ts
  packages/read-importers-context/src/index.ts
  packages/supi/package.json
  packages/supi/src/getContext/index.ts
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/link.ts
  packages/supi/src/link/options.ts
  packages/supi/src/rebuild/extendRebuildOptions.ts
  packages/supi/src/rebuild/index.ts
  pnpm-lock.yaml
Labels: state: in progress, type: breaking change

#2064 fix(pnpm): Add missing command options
  packages/pnpm/src/main.ts
Labels: area: cli, type: bug

#2069 feat: --color
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/config/test/index.ts
  packages/pnpm/src/cmd/help.ts
  packages/pnpm/src/main.ts
Labels: type: feature

#2080 fix: don't fail on missing commands of hoisted dependencies
  packages/build-modules/package.json
  packages/headless/package.json
  packages/hoist/package.json
  packages/hoist/src/index.ts
  packages/supi/package.json
  packages/supi/test/install/lifecycleScripts.ts
  pnpm-lock.yaml
Labels: regression

#2083 refactor(typings): Rename `tape‑promise.d.ts` to `typed.d.ts`
  typings/index.d.ts
  typings/typed.d.ts
Labels: type: refactor

#2084 refactor(typings): Sort third‑party type definitions
  typings/local.d.ts
  typings/typed.d.ts
Labels: type: refactor

#2091 feat: configurable virtual store directory
  packages/config/package.json
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/constants/src/index.ts
  packages/default-reporter/src/reportError.ts
  packages/dependencies-hierarchy/src/index.ts
  packages/headless/src/index.ts
  packages/lockfile-file/README.md
  packages/lockfile-file/src/read.ts
  packages/lockfile-file/src/write.ts
  packages/lockfile-file/test/read.ts
  packages/modules-yaml/src/index.ts
  packages/modules-yaml/test/index.ts
  packages/outdated/package.json
  packages/pnpm/src/cmd/help.ts
  packages/pnpm/src/cmd/outdated.ts
  packages/pnpm/src/main.ts
  packages/pnpm/test/install/misc.ts
  packages/supi/src/getContext/checkCompatibility/UnexpectedVirtualStoreDirError.ts
  packages/supi/src/getContext/checkCompatibility/index.ts
  packages/supi/src/getContext/index.ts
  packages/supi/src/getContext/readLockfiles.ts
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/index.ts
  packages/supi/src/link/index.ts
  packages/supi/src/rebuild/index.ts
  packages/supi/test/install/misc.ts
  packages/supi/test/install/multipleImporters.ts
  packages/supi/test/lockfile.ts
  pnpm-lock.yaml
  privatePackages/assert-project/src/index.ts
  privatePackages/assert-project/test/index.ts
Labels: state: ready for CR

#2098 fix(config): settings are merged in correct order
  packages/config/src/index.ts
  packages/config/test/index.ts
Labels: type: bug

#2099 fix(package‑is‑installable): Use `WantedEngine` and `WantedPlatform`
  packages/package-is-installable/src/checkEngine.ts
  packages/package-is-installable/src/checkPlatform.ts
  packages/package-is-installable/src/index.ts
  packages/pnpm/src/packageIsInstallable.ts
Labels: type: refactor

#2103 fix: don't forward tail args to pre/post scripts
  packages/pnpm/src/cmd/recursive/run.ts
  packages/pnpm/src/cmd/run.ts
  packages/pnpm/test/run.ts
Labels: area: lifecycle-scripts

#2115 feat: --working-dir flag
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/config/test/index.ts
  packages/default-reporter/src/reporterForClient/index.ts
  packages/default-reporter/test/index.ts
  packages/default-reporter/test/reportingProgress.ts
  packages/pnpm/src/cmd/help.ts
  packages/pnpm/src/cmd/import.ts
  packages/pnpm/src/cmd/install.ts
  packages/pnpm/src/cmd/link.ts
  packages/pnpm/src/cmd/list.ts
  packages/pnpm/src/cmd/outdated.ts
  packages/pnpm/src/cmd/publish.ts
  packages/pnpm/src/cmd/rebuild.ts
  packages/pnpm/src/cmd/recursive/index.ts
  packages/pnpm/src/cmd/recursive/outdated.ts
  packages/pnpm/src/cmd/remove.ts
  packages/pnpm/src/cmd/root.ts
  packages/pnpm/src/cmd/run.ts
  packages/pnpm/src/cmd/server/start.ts
  packages/pnpm/src/cmd/server/status.ts
  packages/pnpm/src/cmd/server/stop.ts
  packages/pnpm/src/cmd/store.ts
  packages/pnpm/src/cmd/unlink.ts
  packages/pnpm/src/createLatestManifestGetter.ts
  packages/pnpm/src/createStoreController.ts
  packages/pnpm/src/main.ts
  packages/pnpm/test/outdated.ts
  packages/pnpm/test/recursive/link.ts
  packages/pnpm/test/root.ts
  packages/pnpm/test/unit-tests/getLatestManifest.spec.ts
  packages/supi/src/getContext/index.ts
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/index.ts
  packages/supi/src/link/index.ts
  packages/supi/src/link/options.ts
  packages/supi/src/rebuild/extendRebuildOptions.ts
  packages/supi/src/rebuild/index.ts
  packages/supi/src/storeStatus/extendStoreStatusOptions.ts
  packages/supi/test/breakingChanges.ts
  packages/supi/test/install/multipleImporters.ts
  packages/supi/test/link.ts
  packages/supi/test/lockfile.ts
  packages/supi/test/prune.ts
  packages/supi/test/uninstall.ts
  packages/supi/test/unlink.ts
Labels: type: refactor

#2121 feat: rename pnpm-prefix to global-dir
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/pnpm/src/cmd/help.ts
  packages/pnpm/src/cmd/link.ts
  packages/pnpm/src/main.ts
  packages/pnpm/test/install/global.ts
  packages/supi/README.md
  packages/supi/src/link/index.ts
  packages/supi/test/link.ts
Labels: type: refactor

#2122 feat: rename --working-dir to --dir
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/config/test/index.ts
  packages/default-reporter/src/reporterForClient/index.ts
  packages/default-reporter/test/index.ts
  packages/default-reporter/test/reportingProgress.ts
  packages/pnpm/src/cmd/help.ts
  packages/pnpm/src/cmd/import.ts
  packages/pnpm/src/cmd/install.ts
  packages/pnpm/src/cmd/link.ts
  packages/pnpm/src/cmd/list.ts
  packages/pnpm/src/cmd/outdated.ts
  packages/pnpm/src/cmd/publish.ts
  packages/pnpm/src/cmd/rebuild.ts
  packages/pnpm/src/cmd/recursive/index.ts
  packages/pnpm/src/cmd/recursive/outdated.ts
  packages/pnpm/src/cmd/remove.ts
  packages/pnpm/src/cmd/root.ts
  packages/pnpm/src/cmd/run.ts
  packages/pnpm/src/cmd/server/start.ts
  packages/pnpm/src/cmd/server/status.ts
  packages/pnpm/src/cmd/server/stop.ts
  packages/pnpm/src/cmd/store.ts
  packages/pnpm/src/cmd/unlink.ts
  packages/pnpm/src/createLatestManifestGetter.ts
  packages/pnpm/src/createStoreController.ts
  packages/pnpm/src/main.ts
  packages/pnpm/test/outdated.ts
  packages/pnpm/test/unit-tests/getLatestManifest.spec.ts
  packages/supi/src/getContext/index.ts
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/index.ts
  packages/supi/src/link/index.ts
  packages/supi/src/link/options.ts
  packages/supi/src/rebuild/extendRebuildOptions.ts
  packages/supi/src/rebuild/index.ts
  packages/supi/src/storeStatus/extendStoreStatusOptions.ts
  packages/supi/test/breakingChanges.ts
  packages/supi/test/install/multipleImporters.ts
  packages/supi/test/link.ts
  packages/supi/test/lockfile.ts
  packages/supi/test/prune.ts
  packages/supi/test/uninstall.ts
  packages/supi/test/unlink.ts
Labels: type: refactor
