Repository pnpm/pnpm, pull requests merged in 2019-09, with the labels that each got.

#1988 fix: peers resolution in a monorepo
  packages/resolve-dependencies/src/index.ts
  packages/supi/src/install/resolvePeers.ts
  packages/supi/test/install/peerDependencies.ts
  packages/utils/src/nodeIdUtils.ts
Labels: area: multi-package repo, area: peers, type: bug

#1997 feat: hoisting by pattern
  packages/config/src/PnpmConfigs.ts
  packages/config/src/index.ts
  packages/config/test/index.ts
  packages/default-reporter/src/reportError.ts
  packages/default-reporter/test/reportingErrors.ts
  packages/headless/package.json
  packages/headless/src/index.ts
  packages/headless/test/fixtures/deps-have-lifecycle-scripts/pnpm-lock.yaml
  packages/headless/test/fixtures/has-local-dep/pnpm-lock.yaml
  packages/headless/test/fixtures/has-local-dir-dep/pnpm-lock.yaml
  packages/headless/test/fixtures/prod-dep-is-dev-subdep/pnpm-lock.yaml
  packages/headless/test/fixtures/resolved-peer-deps-in-subdeps/pnpm-lock.yaml
  packages/headless/test/fixtures/side-effects-of-subdep/pnpm-lock.yaml
  packages/headless/test/fixtures/side-effects/pnpm-lock.yaml
  packages/headless/test/fixtures/simple-shamefully-flatten/pnpm-lock.yaml
  packages/headless/test/fixtures/simple-with-more-deps/pnpm-lock.yaml
  packages/headless/test/fixtures/simple-with-optional-dep/pnpm-lock.yaml
  packages/headless/test/fixtures/simple/pnpm-lock.yaml
  packages/headless/test/fixtures/with-1-dep/pnpm-lock.yaml
  packages/headless/test/index.ts
  packages/headless/test/utils/testDefaults.ts
  packages/hoist/README.md
  packages/hoist/package.json
  packages/hoist/src/index.ts
  packages/hoist/tsconfig.json
  packages/hoist/tslint.json
  packages/modules-cleaner/src/prune.ts
  packages/modules-yaml/src/index.ts
  packages/modules-yaml/test/index.ts
  packages/outdated/package.json
  packages/pnpm/package.json
  packages/pnpm/src/cmd/help.ts
  packages/pnpm/src/cmd/recursive/index.ts
  packages/pnpm/src/getConfigs.ts
  packages/pnpm/src/types.ts
  packages/pnpm/test/install/hoist.ts
  packages/pnpm/test/install/index.ts
  packages/pnpm/test/link.ts
  packages/pnpm/test/recursive/misc.ts
  packages/read-importers-context/src/index.ts
  packages/shamefully-flatten/README.md
  packages/supi/package.json
  packages/supi/src/getContext/index.ts
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/index.ts
  packages/supi/src/install/link.ts
  packages/supi/src/link/index.ts
  packages/supi/src/link/options.ts
  packages/supi/src/rebuild/extendRebuildOptions.ts
  packages/supi/src/rebuild/index.ts
  packages/supi/src/storeStatus/extendStoreStatusOptions.ts
  packages/supi/src/storeStatus/index.ts
  packages/supi/test/install/frozenLockfile.ts
  packages/supi/test/install/hoist.ts
  packages/supi/test/install/independentLeaves.ts
  packages/supi/test/install/index.ts
  packages/supi/test/install/lifecycleScripts.ts
  packages/supi/test/install/sideEffects.ts
  pnpm-lock.yaml
  renovate.json
Labels: type: breaking change

#2013 Nicer alignments in the help command output
  packages/pnpm/package.json
  packages/pnpm/src/cmd/help.ts
  pnpm-lock.yaml
Labels: state: ready for CR

#2015 feat(pnpm): Implement `pnpm why`
  packages/pnpm/src/cmd/help.ts
  packages/pnpm/src/cmd/index.ts
  packages/pnpm/src/cmd/list.ts
  packages/pnpm/src/cmd/recursive/index.ts
  packages/pnpm/src/getCommandFullName.ts
  packages/pnpm/src/main.ts
  packages/pnpm/test/list.ts
  packages/pnpm/test/recursive/list.ts
Labels: type: feature

#2016 test(pnpm/utils): Fix `execPnpm.ts`
  packages/pnpm/test/install/selfUpdate.ts
  packages/pnpm/test/monorepo/index.ts
  packages/pnpm/test/recursive/misc.ts
  packages/pnpm/test/server.ts
  packages/pnpm/test/utils/execPnpm.ts
  packages/pnpm/test/utils/index.ts
Labels: type: refactor

#2027 refactor(pnpm): Unify more of `outdated` and `recursive outdated`
  packages/pnpm/src/cmd/outdated.ts
  packages/pnpm/src/cmd/recursive/outdated.ts
Labels: area: cli, type: refactor

#2018 feat: move .pnpm-lock.yaml to .pnpm/
  packages/constants/src/index.ts
  packages/list/test/fixture-with-external-shrinkwrap/node_modules/.pnpm/pnpm-lock.yaml
  packages/list/test/fixture-with-external-shrinkwrap/node_modules/.pnpm/registry.npmjs.org/is-positive/1.0.0/node_modules/is-positive/index.js
  packages/list/test/fixture-with-external-shrinkwrap/node_modules/.pnpm/registry.npmjs.org/is-positive/1.0.0/node_modules/is-positive/license
  packages/list/test/fixture-with-external-shrinkwrap/node_modules/.pnpm/registry.npmjs.org/is-positive/1.0.0/node_modules/is-positive/package.json
  packages/list/test/fixture-with-external-shrinkwrap/node_modules/.pnpm/registry.npmjs.org/is-positive/1.0.0/node_modules/is-positive/readme.md
  packages/list/test/fixture-with-no-pkg-name-and-no-version/node_modules/.pnpm/pnpm-lock.yaml
  packages/list/test/fixture-with-no-pkg-version/node_modules/.pnpm/pnpm-lock.yaml
  packages/list/test/fixture/node_modules/.pnpm/pnpm-lock.yaml
  packages/list/test/index.ts
  packages/list/test/with-aliased-dep/node_modules/.pnpm/pnpm-lock.yaml
  packages/list/test/with-aliased-dep/node_modules/.pnpm/registry.npmjs.org/is-positive/1.0.0/node_modules/is-positive/package.json
  packages/lockfile-file/src/write.ts
  packages/lockfile-file/test/fixtures/1/node_modules/.pnpm/pnpm-lock.yaml
  packages/lockfile-file/test/fixtures/2/node_modules/.pnpm/pnpm-lock.yaml
  packages/pnpm/test/outdated.ts
  packages/pnpm/test/packages/has-not-outdated-deps/node_modules/.pnpm/pnpm-lock.yaml
  packages/pnpm/test/packages/has-outdated-deps-and-external-shrinkwrap/node_modules/.pnpm/pnpm-lock.yaml
  packages/pnpm/test/packages/has-outdated-deps/node_modules/.pnpm/pnpm-lock.yaml
  privatePackages/assert-project/package.json
  privatePackages/assert-project/test/index.ts
Labels: type: breaking change

#2026 feat(outdated): add --no-table option
  packages/config/src/PnpmConfigs.ts
  packages/config/src/index.ts
  packages/pnpm/package.json
  packages/pnpm/src/cmd/help.ts
  packages/pnpm/src/cmd/outdated.ts
  packages/pnpm/src/cmd/recursive/outdated.ts
  packages/pnpm/test/outdated.ts
  packages/pnpm/test/recursive/outdated.ts
  pnpm-lock.yaml
Labels: area: outdated, type: feature

#2032 feat(dependency‑path): Expose `peersSuffix`
  packages/dependency-path/package.json
  packages/dependency-path/src/index.ts
  packages/dependency-path/test/index.ts
  packages/lockfile-utils/src/nameVerFromPkgSnapshot.ts
  packages/lockfile-utils/test/nameVerFromPkgSnapshot.ts
  pnpm-lock.yaml
Labels: area: lockfile, area: peers, type: feature

#2031 feat: cmds should fail on unsupported flags
  packages/pnpm/src/main.ts
  packages/pnpm/test/cli.ts
  packages/pnpm/test/install/misc.ts
  packages/pnpm/test/publish.ts
  packages/pnpm/test/uninstall.ts
  packages/pnpm/test/update.ts
Labels: type: breaking change

#1957 Add packages with the workspace protocol
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/pnpm/src/cmd/help.ts
  packages/pnpm/src/main.ts
  packages/pnpm/test/monorepo/index.ts
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/index.ts
  packages/supi/test/install/multipleImporters.ts
Labels: area: multi-package repo, type: feature
