Repository pnpm/pnpm, pull requests merged in 2020-05, with the labels that each got.

#2512 docs(README): highlight the usage of content-addressable storage
  packages/pnpm/README.md
Labels: area: documentation

#2523 perf: tarballs are not written to the disk
  .changeset/dry-swans-fix.md
  packages/pnpm/test/install/index.ts
  packages/pnpm/test/install/store.ts
  packages/tarball-fetcher/src/createDownloader.ts
  packages/tarball-fetcher/test/download.ts
Labels: area: performance

#2525 perf: read the package manifests from the memory, when possible
  .changeset/neat-beers-sit.md
  .changeset/violet-trainers-fold.md
  packages/cafs/package.json
  packages/cafs/src/addFilesFromDir.ts
  packages/cafs/src/addFilesFromTarball.ts
  packages/cafs/src/checkFilesIntegrity.ts
  packages/cafs/src/parseJson.ts
  packages/fetcher-base/package.json
  packages/fetcher-base/src/index.ts
  packages/fetcher-base/tsconfig.json
  packages/git-fetcher/package.json
  packages/git-fetcher/src/index.ts
  packages/git-fetcher/test/index.ts
  packages/git-fetcher/tsconfig.json
  packages/package-requester/src/packageRequester.ts
  packages/package-requester/src/safeDeferredPromise.ts
  packages/package-requester/test/index.ts
  packages/store-controller-types/src/index.ts
  packages/tarball-fetcher/src/createDownloader.ts
  packages/tarball-fetcher/src/index.ts
  pnpm-lock.yaml
Labels: area: performance

#2527 perf: reduce directory nesting in the store
  .changeset/breezy-maps-double.md
  packages/cafs/src/checkFilesIntegrity.ts
  packages/cafs/src/getFilePathInCafs.ts
  packages/cafs/src/index.ts
  packages/package-requester/src/packageRequester.ts
  packages/package-requester/test/index.ts
  packages/package-store/src/storeController/index.ts
  packages/plugin-commands-store/package.json
  packages/plugin-commands-store/src/storeStatus/index.ts
  packages/plugin-commands-store/test/storeAdd.ts
  packages/plugin-commands-store/test/storePrune.ts
  packages/plugin-commands-store/test/storeStatus.ts
  packages/plugin-commands-store/test/storeUsages.ts
  packages/pnpm/test/install/misc.ts
  packages/supi/test/install/lockfileOnly.ts
  packages/tarball-fetcher/test/download.ts
  pnpm-lock.yaml
  privatePackages/assert-project/src/index.ts
  privatePackages/assert-store/package.json
  privatePackages/assert-store/src/index.ts
Labels: area: performance, type: breaking change

#2529 perf: keep all the metadata files in the same dir
  .changeset/fifty-horses-change.md
  packages/npm-resolver/src/index.ts
  packages/npm-resolver/src/pickPackage.ts
  packages/npm-resolver/test/index.ts
  packages/supi/test/install/lockfileOnly.ts
Labels: area: performance, type: breaking change

#2530 perf: use a suffix for exec files in CAFS, not a dir
  .changeset/lovely-ducks-judge.md
  packages/cafs/src/getFilePathInCafs.ts
  packages/plugin-commands-store/test/storeAdd.ts
Labels: area: performance

#2531 perf: less dirs in the virtual store directory
  .changeset/afraid-taxis-applaud.md
  packages/constants/src/index.ts
  packages/headless/package.json
  packages/headless/test/index.ts
  packages/hoist/package.json
  packages/modules-cleaner/package.json
  packages/modules-cleaner/src/prune.ts
  packages/package-requester/package.json
  packages/package-requester/src/packageRequester.ts
  packages/package-requester/test/index.ts
  packages/package-store/package.json
  packages/plugin-commands-rebuild/package.json
  packages/plugin-commands-rebuild/test/index.ts
  packages/plugin-commands-rebuild/test/recursive.ts
  packages/plugin-commands-store/package.json
  packages/plugin-commands-store/src/storeStatus/index.ts
  packages/plugin-commands-store/test/storeStatus.ts
  packages/pnpm/test/install/global.ts
  packages/pnpm/test/install/misc.ts
  packages/pnpm/test/root.ts
  packages/server/test/index.ts
  packages/supi/package.json
  packages/supi/test/install/fromRepo.ts
  packages/supi/test/install/independentLeaves.ts
  packages/supi/test/install/lifecycleScripts.ts
  packages/supi/test/install/misc.ts
  packages/supi/test/install/multipleImporters.ts
  packages/supi/test/install/optionalDependencies.ts
  packages/supi/test/install/peerDependencies.ts
  packages/supi/test/link.ts
  packages/supi/test/lockfile.ts
  pnpm-lock.yaml
Labels: area: performance, type: breaking change

#2546 Reduce nesting in the virtual store
  .changeset/wet-brooms-drive.md
  packages/headless/src/index.ts
  packages/headless/test/index.ts
  packages/hoist/src/index.ts
  packages/modules-cleaner/src/prune.ts
  packages/plugin-commands-rebuild/src/implementation/index.ts
  packages/plugin-commands-rebuild/test/index.ts
  packages/plugin-commands-store/src/storeStatus/index.ts
  packages/plugin-commands-store/test/storeStatus.ts
  packages/pnpm/test/install/misc.ts
  packages/resolve-dependencies/src/resolveDependencies.ts
  packages/supi/src/install/index.ts
  packages/supi/src/install/link.ts
  packages/supi/src/install/lockfile.ts
  packages/supi/src/install/resolvePeers.ts
  packages/supi/src/install/updateLockfile.ts
  packages/supi/test/install/fromRepo.ts
  packages/supi/test/install/hoist.ts
  packages/supi/test/install/independentLeaves.ts
  packages/supi/test/install/lifecycleScripts.ts
  packages/supi/test/install/misc.ts
  packages/supi/test/install/multipleImporters.ts
  packages/supi/test/install/optionalDependencies.ts
  packages/supi/test/install/peerDependencies.ts
  packages/supi/test/link.ts
  packages/supi/test/lockfile.ts
Labels: type: breaking change

#2532 Allow referencing packages not under the directory containing pnpm-workspace.yaml
  packages/plugin-commands-installation/src/recursive.ts
  packages/pnpm/test/monorepo/index.ts
Labels: area: monorepo

#2553 feat!: remove locking of node_modules
  .changeset/small-jokes-sing.md
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/headless/test/utils/testDefaults.ts
  packages/plugin-commands-installation/src/add.ts
  packages/plugin-commands-installation/src/install.ts
  packages/pnpm/test/install/misc.ts
  packages/store-connection-manager/src/createNewStoreController.ts
  packages/store-connection-manager/src/createResolver.ts
  packages/supi/package.json
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/index.ts
  packages/supi/src/lock.ts
  packages/supi/test/install/independentLeaves.ts
  packages/supi/test/install/misc.ts
  packages/supi/test/utils/testDefaults.ts
  pnpm-lock.yaml
Labels: type: breaking change

#2554 Linking packages to subdependencies
  .changeset/beige-ducks-rescue.md
  .changeset/heavy-eyes-ring.md
  .changeset/serious-geckos-taste.md
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/plugin-commands-installation/src/installDeps.ts
  packages/plugin-commands-installation/src/recursive.ts
  packages/resolve-dependencies/src/index.ts
  packages/resolve-dependencies/src/resolveDependencies.ts
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/index.ts
  packages/supi/src/install/link.ts
  packages/supi/src/install/resolvePeers.ts
  packages/supi/src/install/updateLockfile.ts
  packages/supi/test/install/multipleImporters.ts
Labels: area: lockfile, area: monorepo

#2564 Fix installaltion without lockfile when an up-to-date node_modules is present
  .changeset/fluffy-readers-fry.md
  .changeset/twelve-camels-agree.md
  packages/filter-lockfile/src/filterLockfileByImportersAndEngine.ts
  packages/filter-lockfile/test/filterByImportersAndEngine.ts
  packages/headless/src/index.ts
  packages/modules-cleaner/src/prune.ts
  packages/plugin-commands-rebuild/test/index.ts
  packages/supi/src/install/link.ts
  packages/supi/test/install/optionalDependencies.ts
Labels: type: bug

#2571 feat!: remove independent-leaves=true support
  .changeset/pretty-tips-crash.md
  .changeset/sharp-crabs-change.md
  packages/audit/tsconfig.json
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/config/test/index.ts
  packages/dependencies-hierarchy/example/node_modules/.modules.yaml
  packages/dependencies-hierarchy/fixtureMonorepo/node_modules/.modules.yaml
  packages/get-context/src/index.ts
  packages/headless/src/index.ts
  packages/headless/test/index.ts
  packages/headless/test/utils/testDefaults.ts
  packages/hoist/src/index.ts
  packages/list/example/node_modules/.modules.yaml
  packages/list/src/getPkgInfo.ts
  packages/list/test/fixture-with-external-shrinkwrap/node_modules/.modules.yaml
  packages/list/test/fixture-with-no-pkg-name-and-no-version/node_modules/.modules.yaml
  packages/list/test/fixture-with-no-pkg-version/node_modules/.modules.yaml
  packages/list/test/fixture/node_modules/.modules.yaml
  packages/list/test/with-aliased-dep/node_modules/.modules.yaml
  packages/modules-yaml/README.md
  packages/modules-yaml/src/index.ts
  packages/modules-yaml/test/index.ts
  packages/package-requester/src/index.ts
  packages/package-requester/src/packageRequester.ts
  packages/package-requester/test/index.ts
  packages/package-store/package.json
  packages/package-store/src/storeController/index.ts
  packages/plugin-commands-installation/src/add.ts
  packages/plugin-commands-installation/src/install.ts
  packages/plugin-commands-installation/src/installDeps.ts
  packages/plugin-commands-installation/src/recursive.ts
  packages/plugin-commands-listing/test/index.ts
  packages/plugin-commands-outdated/src/outdated.ts
  packages/plugin-commands-outdated/test/index.ts
  packages/plugin-commands-outdated/test/utils.ts
  packages/plugin-commands-rebuild/src/implementation/index.ts
  packages/plugin-commands-rebuild/src/rebuild.ts
  packages/plugin-commands-rebuild/test/index.ts
  packages/plugin-commands-store/src/storeStatus/extendStoreStatusOptions.ts
  packages/pnpm/src/cmd/root.ts
  packages/pnpm/test/cli.ts
  packages/pnpm/test/utils/execPnpm.ts
  packages/read-projects-context/src/index.ts
  packages/resolve-dependencies/src/resolveDependencies.ts
  packages/server/src/connectStoreController.ts
  packages/server/src/createServer.ts
  packages/server/test/index.ts
  packages/store-controller-types/src/index.ts
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/index.ts
  packages/supi/src/install/link.ts
  packages/supi/src/install/resolvePeers.ts
  packages/supi/src/link/options.ts
  packages/supi/test/breakingChanges.ts
  packages/supi/test/install/independentLeaves.ts
  packages/supi/test/install/index.ts
  packages/supi/test/unlink.ts
  pnpm-lock.yaml
Labels: type: breaking change

#2576 docs(README): update speed description
  packages/pnpm/README.md
Labels: area: documentation

#2578 Improvements to the README file
  packages/pnpm/README.md
Labels: area: documentation

#2579 docs(README): suggest the most reliable installation
  packages/pnpm/README.md
Labels: area: documentation

#2580 fix: installing git-hosted dependencies
  .changeset/violet-steaks-burn.md
  packages/git-fetcher/src/index.ts
  packages/git-fetcher/test/index.ts
  packages/headless/test/utils/testDefaults.ts
  packages/store-connection-manager/src/createNewStoreController.ts
  packages/supi/test/utils/testDefaults.ts
Labels: regression

#2588 fix: install a pkg hosted not under registry domain
  .changeset/cool-pugs-reply.md
  packages/supi/package.json
  packages/supi/src/install/lockfile.ts
  packages/supi/test/lockfile.ts
  pnpm-lock.yaml
  registry-mirror/is-positive-3.1.0.tgz
  registry-mirror/is-positive.json
Labels: regression

#2593 fix(run): infinite recursion
  .changeset/nine-ants-add.md
  .changeset/three-cobras-wave.md
  packages/lifecycle/package.json
  packages/lifecycle/src/runLifecycleHook.ts
  packages/plugin-commands-script-runners/src/runRecursive.ts
  packages/plugin-commands-script-runners/test/runRecursive.ts
  pnpm-lock.yaml
Labels: area: lifecycle-scripts, area: monorepo

#2596 fix: error message during offline installation
  .changeset/great-rocks-compare.md
  .changeset/orange-news-type.md
  packages/fetcher-base/src/index.ts
  packages/package-requester/src/packageRequester.ts
  packages/tarball-fetcher/src/index.ts
  packages/tarball-fetcher/test/download.ts
Labels: type: refactor
