Repository pnpm/pnpm, pull requests merged in 2020-09, with the labels that each got.

#2820 fix: "heap out of memory" error on some huge projects
  .changeset/new-cherries-breathe.md
  packages/supi/src/install/resolvePeers.ts
  packages/supi/test/install/misc.ts
Labels: type: bug

#2845 feat(reporter): show the progress of adding pkgs to virtual store
  .changeset/cuddly-moles-warn.md
  .changeset/long-jeans-attack.md
  .changeset/nice-lies-shout.md
  .changeset/strange-eagles-sin.md
  .changeset/tiny-fishes-nail.md
  packages/core-loggers/src/all.ts
  packages/core-loggers/src/importingLogger.ts
  packages/core-loggers/src/index.ts
  packages/core-loggers/src/progressLogger.ts
  packages/default-reporter/src/index.ts
  packages/default-reporter/src/reporterForClient/index.ts
  packages/default-reporter/src/reporterForClient/reportProgress.ts
  packages/default-reporter/test/reportingProgress.ts
  packages/headless/src/index.ts
  packages/package-store/src/storeController/createImportPackage.ts
  packages/package-store/src/storeController/index.ts
  packages/server/src/connectStoreController.ts
  packages/store-controller-types/src/index.ts
  packages/supi/src/install/link.ts
Labels: area: reporting, type: feature

#2859 feat(run): print info about root workspace scripts
  .changeset/smooth-drinks-do.md
  packages/plugin-commands-script-runners/src/run.ts
  packages/plugin-commands-script-runners/test/index.ts
Labels: type: feature

#2870 fix: import method selection on unknown errors
  .changeset/honest-walls-train.md
  packages/package-store/src/storeController/createImportPackage.ts
  packages/package-store/test/createImportPackage.spec.ts
Labels: regression

#2875 perf: create module directories before linking start
  .changeset/clever-ghosts-cover.md
  packages/headless/src/index.ts
  packages/supi/src/install/link.ts
Labels: area: performance

#2877 refactor: client pkg to jest
  jest.config.js
  packages/client/jest.config.js
  packages/client/package.json
  packages/client/test/index.ts
Labels: type: refactor

#2878 refactor: fetch pkg to jest
  packages/fetch/jest.config.js
  packages/fetch/package.json
  packages/fetch/test/fetchFromRegistry.ts
Labels: type: refactor

#2876 perf: faster integrity verification of the store
  .changeset/funny-pugs-pump.md
  .changeset/fuzzy-numbers-wink.md
  .changeset/loud-walls-run.md
  packages/cafs/package.json
  packages/cafs/src/addFilesFromDir.ts
  packages/cafs/src/addFilesFromTarball.ts
  packages/cafs/src/checkFilesIntegrity.ts
  packages/cafs/src/getFilePathInCafs.ts
  packages/cafs/src/index.ts
  packages/cafs/test/fixtures/one-file/foo.txt
  packages/cafs/test/index.ts
  packages/fetcher-base/src/index.ts
  packages/git-fetcher/test/index.ts
  packages/package-requester/src/packageRequester.ts
  packages/package-requester/test/index.ts
  packages/package-store/src/storeController/index.ts
  packages/store-controller-types/src/index.ts
  pnpm-lock.yaml
Labels: area: performance

#2881 feat: shell emulator
  .changeset/early-hounds-sneeze.md
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/lifecycle/package.json
  packages/lifecycle/src/index.ts
  packages/lifecycle/src/runLifecycleHook.ts
  packages/lifecycle/src/runLifecycleHooksConcurrently.ts
  packages/plugin-commands-installation/src/installDeps.ts
  packages/plugin-commands-rebuild/src/implementation/extendRebuildOptions.ts
  packages/plugin-commands-rebuild/src/implementation/index.ts
  packages/plugin-commands-rebuild/src/rebuild.ts
  packages/plugin-commands-script-runners/src/run.ts
  packages/plugin-commands-script-runners/src/runRecursive.ts
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/index.ts
  pnpm-lock.yaml
Labels: type: feature

#1874 feat: Plug'n'Play
  .changeset/rotten-numbers-joke.md
  package.json
  packages/lockfile-to-pnp/README.md
  packages/lockfile-to-pnp/jest.config.js
  packages/lockfile-to-pnp/package.json
  packages/lockfile-to-pnp/src/createPnpBin.ts
  packages/lockfile-to-pnp/src/index.ts
  packages/lockfile-to-pnp/test/index.ts
  packages/lockfile-to-pnp/tsconfig.json
  packages/lockfile-to-pnp/tsconfig.lint.json
  pnpm-lock.yaml
Labels: Yarn compat, type: feature

#2898 feat: excluding packages using --filter
  .changeset/hip-lemons-rescue.md
  packages/common-cli-options-help/src/index.ts
  packages/filter-workspace-packages/src/index.ts
  packages/filter-workspace-packages/src/parsePackageSelector.ts
  packages/filter-workspace-packages/test/index.ts
  packages/filter-workspace-packages/test/parsePackageSelector.ts
Labels: type: feature
