Repository pnpm/pnpm, pull requests merged in 2020-01, with the labels that each got.

#2243 refactor: don't use the same handlers for different commands
  packages/plugin-commands-audit/src/audit.ts
  packages/plugin-commands-audit/test/index.ts
  packages/plugin-commands-installation/src/add.ts
  packages/plugin-commands-installation/src/install.ts
  packages/plugin-commands-installation/src/link.ts
  packages/plugin-commands-installation/src/recursive.ts
  packages/plugin-commands-installation/src/update.ts
  packages/plugin-commands-installation/test/linkRecursive.ts
  packages/plugin-commands-installation/test/miscRecursive.ts
  packages/plugin-commands-installation/test/updateRecursive.ts
  packages/plugin-commands-listing/src/index.ts
  packages/plugin-commands-listing/src/list.ts
  packages/plugin-commands-listing/src/ll.ts
  packages/plugin-commands-listing/src/recursive.ts
  packages/plugin-commands-listing/src/why.ts
  packages/plugin-commands-listing/test/index.ts
  packages/plugin-commands-listing/test/recursive.ts
  packages/plugin-commands-outdated/src/outdated.ts
  packages/plugin-commands-outdated/test/index.ts
  packages/plugin-commands-outdated/test/recursive.ts
  packages/plugin-commands-publishing/src/pack.ts
  packages/plugin-commands-publishing/src/publish.ts
  packages/plugin-commands-publishing/src/recursivePublish.ts
  packages/plugin-commands-publishing/test/pack.ts
  packages/plugin-commands-publishing/test/publish.ts
  packages/pnpm/src/cmd/installTest.ts
  packages/pnpm/src/main.ts
Labels: state: in progress, type: refactor

#2252 feat: outdated --dev | --production | --no-optional
  fixtures/has-outdated-deps/node_modules/.pnpm/lock.yaml
  fixtures/has-outdated-deps/package.json
  fixtures/has-outdated-deps/pnpm-lock.yaml
  packages/outdated/src/index.ts
  packages/plugin-commands-outdated/src/outdated.ts
  packages/plugin-commands-outdated/src/recursive.ts
  packages/plugin-commands-outdated/test/index.ts
  packages/plugin-commands-outdated/test/recursive.ts
Labels: type: feature

#2254 feat: filtering by location including deps/dependents
  packages/common-cli-options-help/src/index.ts
  packages/filter-workspace-packages/src/index.ts
  packages/filter-workspace-packages/src/parsePackageSelector.ts
  packages/filter-workspace-packages/test/index.ts
  packages/filter-workspace-packages/test/parsePackageSelector.ts
Labels: area: monorepo, type: feature

#2256 feat(outdated): --compatible
  fixtures/has-major-outdated-deps/.gitignore
  fixtures/has-major-outdated-deps/.npmrc
  fixtures/has-major-outdated-deps/node_modules/.pnpm/lock.yaml
  fixtures/has-major-outdated-deps/package.json
  fixtures/has-major-outdated-deps/pnpm-lock.yaml
  packages/outdated/package.json
  packages/outdated/src/index.ts
  packages/plugin-commands-outdated/src/createLatestManifestGetter.ts
  packages/plugin-commands-outdated/src/outdated.ts
  packages/plugin-commands-outdated/test/getLatestManifest.spec.ts
  packages/plugin-commands-outdated/test/index.ts
  pnpm-lock.yaml
Labels: area: outdated, type: feature

#2258 fix(outdated): print different current versions separately
  packages/plugin-commands-outdated/src/recursive.ts
  packages/plugin-commands-outdated/src/utils.ts
  packages/plugin-commands-outdated/test/recursive.ts
Labels: area: monorepo, area: outdated, type: bug

#2259 fix: resolving packages in a monorepo
  packages/npm-resolver/src/index.ts
  packages/npm-resolver/test/index.ts
  packages/supi/src/install/index.ts
Labels: area: monorepo, regression, type: bug

#2267 fix: CLI output with --parseable
  packages/pnpm/src/main.ts
  packages/pnpm/test/monorepo/index.ts
Labels: area: cli, type: bug

#2270 fix(rm): --save-dev|--save-optional|--save-prod
  packages/plugin-commands-installation/src/remove.ts
  packages/supi/src/uninstall/removeDeps.ts
Labels: type: bug

#2271 feat: interactive update
  packages/default-reporter/src/index.ts
  packages/plugin-commands-installation/package.json
  packages/plugin-commands-installation/src/getUpdateChoices.ts
  packages/plugin-commands-installation/src/install.ts
  packages/plugin-commands-installation/src/update.ts
  packages/plugin-commands-installation/test/getUpdateChoices.spec.ts
  packages/plugin-commands-installation/test/index.ts
  packages/plugin-commands-installation/test/updateInteractive.ts
  packages/pnpm/src/main.ts
  pnpm-lock.yaml
Labels: type: feature

#2280 feat: add validation for readPackage hook's return manifest's dependencies property
  packages/pnpmfile/src/requirePnpmfile.ts
  packages/pnpmfile/test/index.ts
  packages/pnpmfile/test/pnpmfiles/readPackageNoObject.js
  packages/pnpmfile/test/pnpmfiles/readPackageNoReturn.js
Labels: area: pnpmfile

#2281 feat: support autocompletion
  packages/cli-utils/package.json
  packages/cli-utils/src/getOptionType.ts
  packages/cli-utils/src/index.ts
  packages/cli-utils/src/optionTypesToCompletions.ts
  packages/cli-utils/src/readDepNameCompletions.ts
  packages/cli-utils/test/getOptionType.test.ts
  packages/cli-utils/test/index.ts
  packages/cli-utils/test/optionTypesToCompletions.test.ts
  packages/command/README.md
  packages/command/package.json
  packages/command/src/index.ts
  packages/command/tsconfig.json
  packages/parse-cli-args/src/index.ts
  packages/parse-cli-args/test/index.ts
  packages/plugin-commands-installation/package.json
  packages/plugin-commands-installation/src/remove.ts
  packages/plugin-commands-installation/src/update/index.ts
  packages/plugin-commands-installation/test/index.ts
  packages/plugin-commands-installation/test/remove/completion.ts
  packages/plugin-commands-outdated/package.json
  packages/plugin-commands-outdated/src/outdated.ts
  packages/plugin-commands-script-runners/package.json
  packages/plugin-commands-script-runners/src/run.ts
  packages/plugin-commands-script-runners/test/index.ts
  packages/plugin-commands-script-runners/test/runCompletion.ts
  packages/pnpm/package.json
  packages/pnpm/src/bin/pnpm.ts
  packages/pnpm/src/cmd/complete.ts
  packages/pnpm/src/cmd/completion.ts
  packages/pnpm/src/cmd/index.ts
  packages/pnpm/src/main.ts
  packages/pnpm/src/parseCliArgs.ts
  packages/pnpm/src/shortHands.ts
  packages/pnpm/test/complete.test.ts
  packages/pnpm/test/index.ts
  pnpm-lock.yaml
  typings/local.d.ts
  typings/typed.d.ts
Labels: state: in progress

#2292 feat: update can use scope to update all scoped packages
  packages/plugin-commands-installation/package.json
  packages/plugin-commands-installation/src/install.ts
  packages/plugin-commands-installation/src/recursive.ts
  packages/plugin-commands-installation/src/update/index.ts
  packages/plugin-commands-installation/test/index.ts
  packages/plugin-commands-installation/test/update/recursive.ts
  packages/plugin-commands-installation/test/update/update.ts
  pnpm-lock.yaml
Labels: type: feature

#2303 fix: finding pnpm's main manifest location
  packages/cli-utils/package.json
  packages/cli-utils/src/pnpmPkgJson.ts
  packages/store-connection-manager/package.json
  packages/store-connection-manager/src/runServerInBackground.ts
  pnpm-lock.yaml
Labels: regression
