Repository pnpm/pnpm, pull requests merged in 2020-02, with the labels that each got.

#2305 fix: pnpm update -r --prod
  packages/plugin-commands-installation/src/install.ts
  packages/plugin-commands-installation/src/installDeps.ts
  packages/plugin-commands-installation/src/recursive.ts
  packages/plugin-commands-installation/src/update/index.ts
  packages/plugin-commands-installation/test/add.ts
  packages/plugin-commands-installation/test/update/recursive.ts
  packages/plugin-commands-installation/test/update/update.ts
  packages/supi/src/install/extendInstallOptions.ts
  packages/supi/src/install/getWantedDependencies.ts
  packages/supi/src/install/index.ts
  packages/utils/src/filterDependenciesByType.ts
  packages/utils/src/index.ts
Labels: area: monorepo, type: bug

#2312 fix: add --save-dev -r
  packages/cli-utils/src/getSaveType.ts
  packages/config/src/index.ts
  packages/plugin-commands-installation/package.json
  packages/plugin-commands-installation/src/recursive.ts
  packages/plugin-commands-installation/test/add.ts
  packages/plugin-commands-installation/test/addRecursive.ts
  packages/plugin-commands-installation/test/index.ts
  packages/pnpm/test/install/misc.ts
  pnpm-lock.yaml
Labels: state: in progress, type: bug

#2322 fix: hoisting in a workspace
  packages/filter-lockfile/src/filterLockfileByImporters.ts
  packages/hoist/src/index.ts
  packages/lockfile-walker/src/index.ts
  packages/plugin-commands-rebuild/src/implementation/index.ts
  packages/supi/test/install/hoist.ts
Labels: area: monorepo, type: bug

#2328 feat(pnpm): Deprecate `pnpm r` alias of `pnpm remove`
  packages/pnpm/src/main.ts
Labels: area: cli, type: breaking change

#2330 fix(pnpm): Fail on unknown command
  packages/parse-cli-args/src/index.ts
  packages/parse-cli-args/test/index.ts
  packages/pnpm/src/cmd/index.ts
  packages/pnpm/src/main.ts
  packages/pnpm/src/reporter/index.ts
  packages/pnpm/test/cli.ts
Labels: area: cli

#2356 perf(dependencies-hierarchy): cache previously found dependencies in getTree
  packages/dependencies-hierarchy/src/index.ts
Labels: area: performance

#2376 -D is an alias of --dev, -P is an alias of --production
  packages/cli-utils/src/getOptionType.ts
  packages/parse-cli-args/src/index.ts
  packages/parse-cli-args/test/index.ts
  packages/plugin-commands-audit/src/audit.ts
  packages/plugin-commands-installation/src/install.ts
  packages/plugin-commands-installation/src/update/index.ts
  packages/plugin-commands-listing/src/list.ts
  packages/plugin-commands-outdated/src/outdated.ts
  packages/pnpm/src/cmd/complete.ts
  packages/pnpm/src/cmd/completion.ts
  packages/pnpm/src/cmd/index.ts
  packages/pnpm/src/parseCliArgs.ts
  packages/pnpm/src/shorthands.ts
  packages/pnpm/test/complete.test.ts
Labels: type: feature

#2383 feat: check branch is master, clean and up to date before publish
  packages/config/src/Config.ts
  packages/config/src/index.ts
  packages/plugin-commands-publishing/package.json
  packages/plugin-commands-publishing/src/gitChecks.ts
  packages/plugin-commands-publishing/src/publish.ts
  packages/plugin-commands-publishing/test/gitChecks.ts
  packages/plugin-commands-publishing/test/index.ts
  pnpm-lock.yaml
Labels: area: publishing, type: feature

#2384 fix: don't create a broken lockfile
  packages/default-reporter/src/reportError.ts
  packages/get-context/src/index.ts
  packages/supi/src/install/index.ts
  packages/supi/test/breakingChanges.ts
  packages/supi/test/install/only.ts
  packages/supi/test/lockfile.ts
Labels: area: lockfile, type: bug
