Repository pnpm/pnpm, pull requests merged in 2021-04, with the labels that each got.

#3306 feat!: do not execute `prepublish` during installation
  .changeset/three-dodos-fail.md
  packages/pnpm/test/monorepo/index.ts
  packages/supi/src/install/index.ts
Labels: type: breaking change

#3307 fix: don't print update notification when installing pnpm first time
  packages/cli-meta/src/index.ts
  packages/pnpm/package.json
  packages/pnpm/test/cli.ts
  pnpm-lock.yaml
Labels: type: bug

#3314 fix: use + instead of # in package paths inside node_modules/.pnpm
  .changeset/shiny-olives-wash.md
  packages/dependency-path/src/index.ts
  packages/dependency-path/test/index.ts
  packages/mount-modules/test/__snapshots__/makeVirtualNodeModules.test.ts.snap
  packages/mount-modules/test/createFuseHandlers.test.ts
  packages/supi/test/install/peerDependencies.ts
Labels: regression

#3320 fix(headless): forward extraBinPaths to runLifecycleHookConcurrently
  .changeset/nasty-lizards-dance.md
  packages/headless/src/index.ts
Labels: type: bug

#3411 fix(cafs): use graceful-fs for reading files
  .changeset/six-crews-work.md
  packages/cafs/package.json
  packages/cafs/src/checkFilesIntegrity.ts
  pnpm-lock.yaml
Labels: regression
